name: adakoop
lcurr: 100
lstep: 30
nu: 1e-3
gamma: 1e-2
kernel_type: rbf
lambda_A: 1e-5
em_iters: 3
em_tol: 1e-6
r_init: 1e-2
burnin: 30
chi2_p: 0.99
cusum_h: null
exceed_rate_th: 0.05
state_reset_P_scale: 1e3
jitter: 1e-10
compress: True
add_dict: True
online_update: True
return_fitting: True
train_rate: 0.2
test_rate: 0.7